<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>as24net-import</AssemblyName>
    <RootNamespace>AS24Net.Import</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AS24Net.Import.Tests" />
  </ItemGroup>

</Project>
